apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-app
  labels:
    app: ping-pong-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      containers:
      - name: ping-pong-app
        image: dwifprasetyo/jenkins-test
        ports:
        - containerPort: 80
